version: '3'

services:
  influxdb:
    image: influxdb:2.7-alpine
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=influxdb
      - DOCKER_INFLUXDB_INIT_BUCKET=speedstar
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    ports:
      - 8087:8086
    networks:
      - influxdb
  speedstar:
    build:
      context: .
      args:
        - PROJECT_VERSION=1.0.0
    container_name: speedstar
    hostname: speedstar
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=
      - INFLUXDB_ORG=influxdb
      - INFLUXDB_BUCKET=speedstar
      - SCHEDULE_CRON=0 */4 * * *
    networks:
      - influxdb
    depends_on:
      - influxdb

volumes:
  influxdb_data: {}

networks:
  influxdb:
