version: '3'

services:
  influxdb:
    image: influxdb:2.7-alpine
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=influxdb
      - DOCKER_INFLUXDB_INIT_BUCKET=speedstar
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb_data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    ports:
      - 8087:8086
    networks:
      - influxdb

volumes:
  influxdb_data: {}

networks:
  influxdb:
